### ISSUE TITLE
Enhancement. add percentage complete

### ISSUE THREAD

**Issue by maddeezy** [IBM/gantt-chart#10]
First of all, great project!

For each "activity" our API is returning percent_complete

Is it possible to add progress?

**Comment by delhoume** [comment]
You may want to have a look at Guildes / Timeline / Activity Rendering, this section explains how to add renderers for custom Activities attributes

**Comment by reregaga** [comment]
In the timeline, you can show the percentage as a bg color of task (need user-defined css rules) and as a label:
js:
```js
{
  data: ganttData,
  ...
  timeTable : {
    renderer : {
      classes(task) {
        return [`classForShowPercent${task.percent_complete}`]
      },
      text(task) {
        return `${task.name} ${task.percent_complete}%`
      },
    }
  }
}
```
css:
```css
...
.classForShowPercent79{ background-color: pink; }
.classForShowPercent80{ background-color: red; }
.classForShowPercent81{ background-color: darkred; }
```
In the table on the left, the percentage can be shown in a separate column, also with bg colors from palette:
```js
{
  data: ganttData,
  ...
  table: {
    columns: [
      ...,
      {
        title: 'Percent',
        renderer: {
          text(task) { return task.percent_complete },
          background: {
            getValue(task) { return task.percent_complete },
            values: ['80', '81'],
            palette: ['red', 'darkred'],
          },
          color: 'automatic',
        },
      }
    ]
  }
}
```
